### ISSUE TITLE
PageRank Sink ?

### ISSUE THREAD

**Issue by carlosengers** [DavidPynes/Tutorials#1]
Hi David,
I am impressed on the tutorials you deliver. Great work.
So i was experimenting on a specific example: pagerank.

I think that the c++ code contains a flaw: the 'sink' is not working as expected.
- The branch is not invoked and even when it was invoked, 
- it should loop over all other nodes.

Effect is reproducible by  removing all edges of the node 'Fb' in the source code.
The immediate result is that the sum of pagerank  is not equal to 1.

Kind regards Carlo

**Comment by DavidPynes** [comment]
Hi Carlo,

Thank you for pointing this issue out. _Sink_ calculations have been updated.

-David
